name: Python application

on:
  schedule:
    - cron: "0 12 * * 2"   # every Tuesday 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run league ID fetcher
        run: python league_ids.py

      - name: Run roster fetcher
        run: python rosters.py

      - name: Commit and push all CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/LeagueIDs_AllYears.csv data/Rosters_AllYears.csv
          git commit -m "Auto-update League + Roster CSVs" || echo "No changes to commit"
          git push


      - name: List CSVs
        run: ls -l data/
          
