name: Update League IDs

on:
  schedule:
    # Runs every Friday at 18:00 UTC (change as needed)
    - cron: '0 18 * * FRI'
  workflow_dispatch:   # allows manual run from Actions page

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas; fi

      - name: Run league id script
        run: |
          python league_ids.py

      - name: Commit and push CSV output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/LeagueIDs_AllYears.csv
          git commit -m "Auto-update LeagueIDs_AllYears.csv" || echo "No changes to commit"
          git push
