name: Python application

on:
  workflow_dispatch:
    inputs:
      script_to_run:
        description: 'Specify which Python script to run (league_ids, rosters, users, rosterhistory, matchups, players, transactions, drafts, Results_RegularSeason, all)'
        required: true
        default: 'all'
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 07:00 UTC (3 AM ET)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run selected script(s)
        run: |
          # Default to 'all' if no manual input was provided
          SCRIPT_TO_RUN="${{ github.event.inputs.script_to_run }}"
          if [ -z "$SCRIPT_TO_RUN" ]; then
              SCRIPT_TO_RUN="all"
          fi

          echo "Selected script: $SCRIPT_TO_RUN"

          if [ "$SCRIPT_TO_RUN" = "league_ids" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python league_ids.py
          fi
          if [ "$SCRIPT_TO_RUN" = "rosters" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python rosters.py
          fi
          if [ "$SCRIPT_TO_RUN" = "users" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python users.py
          fi
          if [ "$SCRIPT_TO_RUN" = "players" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python players.py
          fi
          if [ "$SCRIPT_TO_RUN" = "rosterhistory" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python rosterhistory.py
          fi
          if [ "$SCRIPT_TO_RUN" = "matchups" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python league_matchups.py
          fi
          if [ "$SCRIPT_TO_RUN" = "transactions" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python league_transactions.py
          fi
          if [ "$SCRIPT_TO_RUN" = "drafts" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python league_drafts.py
          fi
          if [ "$SCRIPT_TO_RUN" = "Results_RegularSeason" ] || [ "$SCRIPT_TO_RUN" = "all" ]; then
              python Results_RegularSeason.py
          fi

          pwd
          ls -R


          # Finally, update the timestamp tracker
          python $GITHUB_WORKSPACE/update_tracker.py

      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Auto-update CSVs" || echo "No changes to commit"
          git push

      - name: List CSVs
        run: ls -l data/
