name: Python application

on:
  workflow_dispatch:
    inputs:
      script_to_run:
        description: 'Specify which Python script to run (league_ids, rosters, users, rosterhistory, matchups, transactions, drafts, Results_RegularSeason, all)'
        required: true
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run selected script
        run: |
          echo "Selected script: ${{ github.event.inputs.script_to_run }}"
          if [ "${{ github.event.inputs.script_to_run }}" = "league_ids" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python league_ids.py
          fi
          if [ "${{ github.event.inputs.script_to_run }}" = "rosters" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python rosters.py
          fi
          if [ "${{ github.event.inputs.script_to_run }}" = "users" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python users.py
          fi
          if [ "${{ github.event.inputs.script_to_run }}" = "rosterhistory" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python rosterhistory.py
          fi          
          if [ "${{ github.event.inputs.script_to_run }}" = "matchups" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python league_matchups.py
          fi
          if [ "${{ github.event.inputs.script_to_run }}" = "transactions" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python league_transactions.py
          fi
          if [ "${{ github.event.inputs.script_to_run }}" = "drafts" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python league_drafts.py
          fi
          if [ "${{ github.event.inputs.script_to_run }}" = "Results_RegularSeason" ] || [ "${{ github.event.inputs.script_to_run }}" = "all" ]; then
              python Results_RegularSeason.py
          fi

      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Auto-update CSVs" || echo "No changes to commit"
          git push

      - name: List CSVs
        run: ls -l data/
